version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    container_name: potato-backend

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    container_name: potato-frontend
    depends_on:
      - backend